/**
 * Real EVM delivery: submit the dWallet-signed EIP-712 authorization to the deployed
 * `MintController` (contracts/evm/src/MintController.sol). The relayer only pays gas;
 * the contract verifies the dWallet signature, the ledger binding and the nonce.
 *
 * Deployed controllers are read from `deployments/evm.json` (written by `pnpm deploy:evm`).
 * Ika returns 64-byte `r||s` ECDSA signatures; the contract accepts them as-is and tries both
 * recovery ids, so no `v` byte is appended here.
 */
import { chainById, toHex, type Authorization } from '@ika-rwa/ledger-sdk';
import { createPublicClient, createWalletClient, http, type Address, type Hex, type PublicClient } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { sepolia, baseSepolia, tempoModerato } from 'viem/chains';
import { createClient as createTempoClient, Addresses as TempoAddresses } from 'viem/tempo';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { repoRoot } from '../config.js';
import type { Delivery } from './mock.js';

const AUTHORIZED_EVENT = {
  type: 'event', name: 'Authorized', anonymous: false,
  inputs: [
    { name: 'action', type: 'uint8', indexed: true }, { name: 'amount', type: 'uint256', indexed: false },
    { name: 'account', type: 'address', indexed: true }, { name: 'nonce', type: 'uint256', indexed: true },
  ],
} as const;

export const MINT_CONTROLLER_ABI = [
  {
    type: 'function', name: 'mintWithAuthorization', stateMutability: 'nonpayable', outputs: [],
    inputs: [
      { name: 'a', type: 'tuple', components: [
        { name: 'action', type: 'uint8' }, { name: 'amount', type: 'uint256' }, { name: 'account', type: 'bytes32' },
        { name: 'nonce', type: 'uint256' }, { name: 'ledger', type: 'bytes32' },
      ] },
      { name: 'sig', type: 'bytes' },
    ],
  },
  {
    type: 'function', name: 'burnWithAuthorization', stateMutability: 'nonpayable', outputs: [],
    inputs: [
      { name: 'a', type: 'tuple', components: [
        { name: 'action', type: 'uint8' }, { name: 'amount', type: 'uint256' }, { name: 'account', type: 'bytes32' },
        { name: 'nonce', type: 'uint256' }, { name: 'ledger', type: 'bytes32' },
      ] },
      { name: 'sig', type: 'bytes' },
    ],
  },
  { type: 'function', name: 'usedNonces', stateMutability: 'view', inputs: [{ name: 'nonce', type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'a', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'DOMAIN_SEPARATOR', stateMutability: 'view', inputs: [], outputs: [{ type: 'bytes32' }] },
  AUTHORIZED_EVENT,
  { type: 'error', name: 'InvalidSignature', inputs: [] },
  { type: 'error', name: 'NonceUsed', inputs: [{ name: 'nonce', type: 'uint256' }] },
  { type: 'error', name: 'WrongLedger', inputs: [] },
  { type: 'error', name: 'WrongAction', inputs: [] },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
] as const;

/** One entry per EVM chain id in `deployments/evm.json`. */
export interface EvmDeployment {
  chainKey: string;
  chainId: number;
  mintController: Address;
  dwalletSigner: Address;
  ledger: Hex;
  domainSeparator: Hex;
  treasury: Address;
  deployer: Address;
  explorer: string;
  txHash: Hex;
  rpcUrl: string;
  feeToken?: Address;
}
export type EvmDeployments = Record<string, EvmDeployment>;

/** Reads `deployments/evm.json`; `{}` when no EVM controller has been deployed yet. */
export function loadEvmDeployments(path = process.env.EVM_DEPLOYMENTS_FILE ?? resolve(repoRoot(), 'deployments/evm.json')): EvmDeployments {
  if (!existsSync(path)) return {};
  return JSON.parse(readFileSync(path, 'utf8')) as EvmDeployments;
}

/** Relayer private key: `EVM_RELAYER_KEY`, else the deployer key generated by `pnpm deploy:evm`. */
export function loadRelayerKey(): Hex {
  if (process.env.EVM_RELAYER_KEY) return process.env.EVM_RELAYER_KEY as Hex;
  if (process.env.EVM_DEPLOYER_KEY) return process.env.EVM_DEPLOYER_KEY as Hex;
  const path = resolve(repoRoot(), 'keys/evm-deployer.json');
  if (!existsSync(path)) throw new Error('no EVM relayer key: set EVM_RELAYER_KEY or run pnpm deploy:evm');
  return (JSON.parse(readFileSync(path, 'utf8')) as { privateKey: Hex }).privateKey;
}

const VIEM_CHAINS = { 11155111: sepolia, 84532: baseSepolia, 42431: tempoModerato } as const;

export interface DeliverEvmParams {
  /** Ledger chain id (2 Ethereum, 3 Base, 5 Tempo). */
  chainId: number;
  auth: Authorization;
  /** Full EIP-712 message bytes (unused on-chain; kept for logging / audit). */
  message?: Uint8Array;
  /** 64-byte r||s from Ika (65-byte r||s||v also accepted). */
  signature: Uint8Array;
  evmDeployments?: EvmDeployments;
  relayerKey?: Hex;
}

export async function deliverEvm(p: DeliverEvmParams): Promise<Delivery> {
  const meta = chainById(p.chainId);
  if (!meta.evmChainId) throw new Error(`${meta.name} is not an EVM chain`);
  const deployments = p.evmDeployments ?? loadEvmDeployments();
  const dep = deployments[String(meta.evmChainId)];
  if (!dep) throw new Error(`no MintController deployed on ${meta.name} (${meta.testnet}); run pnpm deploy:evm`);
  const account = privateKeyToAccount(p.relayerKey ?? loadRelayerKey());
  const chain = VIEM_CHAINS[meta.evmChainId as keyof typeof VIEM_CHAINS];
  if (!chain) throw new Error(`unsupported EVM chain id ${meta.evmChainId}`);
  const transport = http(dep.rpcUrl);
  const publicClient = createPublicClient({ chain, transport });

  const authArg = {
    action: p.auth.action,
    amount: p.auth.amount,
    account: `0x${toHex(p.auth.account).padStart(64, '0')}` as Hex,
    nonce: p.auth.nonce,
    ledger: `0x${toHex(p.auth.ledger)}` as Hex,
  };
  const sig = `0x${toHex(p.signature)}` as Hex;
  const functionName = p.auth.action === 0 ? 'mintWithAuthorization' : 'burnWithAuthorization';

  // Idempotent: a run that timed out after its transaction landed must not deliver twice.
  const prior = await findEvmDelivery(publicClient as PublicClient, dep, p.auth.nonce);
  if (prior) {
    return {
      txHash: prior.hash,
      txHashBytes: Uint8Array.from(Buffer.from(prior.hash.slice(2), 'hex')),
      explorer: meta.explorerTx(prior.hash),
      note: `already ${p.auth.action === 0 ? 'minted' : 'burned'} on ${meta.name} (${meta.testnet}) in block ${prior.blockNumber}; recording that transaction`,
    };
  }

  let hash: Hex;
  if (meta.evmChainId === 42431) {
    // Tempo: stablecoin-denominated fees via the 0x76 transaction type; viem's Tempo client serializes it.
    const tempo = createTempoClient({ account, chain: tempoModerato, transport, feeToken: dep.feeToken ?? TempoAddresses.pathUsd });
    hash = await tempo.writeContract({ address: dep.mintController, abi: MINT_CONTROLLER_ABI, functionName, args: [authArg, sig] });
  } else {
    const wallet = createWalletClient({ account, chain, transport });
    hash = await wallet.writeContract({ address: dep.mintController, abi: MINT_CONTROLLER_ABI, functionName, args: [authArg, sig] });
  }
  const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 180_000 });
  if (receipt.status !== 'success') throw new Error(`${meta.name} tx ${hash} reverted`);
  return {
    txHash: hash,
    txHashBytes: Uint8Array.from(Buffer.from(hash.slice(2), 'hex')),
    explorer: meta.explorerTx(hash),
    note: `${p.auth.action === 0 ? 'minted' : 'burned'} on ${meta.name} (${meta.testnet}) via MintController ${dep.mintController}, block ${receipt.blockNumber}`,
  };
}

/** The transaction that consumed `nonce` on this controller, if any. */
async function findEvmDelivery(c: PublicClient, dep: EvmDeployment, nonce: bigint): Promise<{ hash: Hex; blockNumber: bigint } | null> {
  const used = await c.readContract({ address: dep.mintController, abi: MINT_CONTROLLER_ABI, functionName: 'usedNonces', args: [nonce] });
  if (!used) return null;
  const { blockNumber: fromBlock } = await c.getTransactionReceipt({ hash: dep.txHash });
  const logs = await c.getLogs({
    address: dep.mintController,
    event: AUTHORIZED_EVENT,
    args: { nonce },
    fromBlock,
    toBlock: 'latest',
  });
  const log = logs[0];
  if (!log?.transactionHash || log.blockNumber === null) throw new Error(`nonce ${nonce} is used on ${dep.chainKey} but its Authorized event was not found`);
  return { hash: log.transactionHash, blockNumber: log.blockNumber };
}

/** Back-compat wrapper for the previous `evmDeliver(cfg, auth, signature)` call in `executor/src/index.ts`. */
export interface EvmDeliverConfig {
  rpcUrl?: string;
  mintController?: Address;
  privateKey?: Hex;
  explorerTx?: (hash: string) => string;
  chainId?: number;
}
export async function evmDeliver(cfg: EvmDeliverConfig, auth: Authorization, signature: Uint8Array): Promise<Delivery> {
  if (cfg.chainId === undefined) throw new Error('evmDeliver: chainId required (use deliverEvm)');
  return deliverEvm({ chainId: cfg.chainId, auth, signature, relayerKey: cfg.privateKey });
}

/** TBILL balance of `account` on the chain's MintController (base units). */
export async function evmBalanceOf(chainId: number, account: Uint8Array): Promise<bigint> {
  const meta = chainById(chainId);
  const dep = loadEvmDeployments()[String(meta.evmChainId)];
  if (!dep) throw new Error(`no MintController deployed on ${meta.name}`);
  const chain = VIEM_CHAINS[meta.evmChainId as keyof typeof VIEM_CHAINS];
  const client = createPublicClient({ chain, transport: http(dep.rpcUrl) });
  return client.readContract({
    address: dep.mintController,
    abi: MINT_CONTROLLER_ABI,
    functionName: 'balanceOf',
    args: [`0x${toHex(account).slice(-40)}` as Address],
  }) as Promise<bigint>;
}
